import type { InputData } from "./types";

export const inputsData: InputData[] = [
  {
    id: "1",
    name: "name",
    label: "Name",
    type: "text",
    placeholder: "Enter your name...",
    errorMessage: "Please enter your name",
    pattern: ".{2,60}",
    required: true,
  },
  {
    id: "2",
    name: "email",
    type: "email",
    placeholder: "Enter your email...",
    errorMessage: "It should be a valid email address!",
    label: "Email",
    pattern: "^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}$",
    required: true,
  },
  {
    id: "3",
    name: "subject",
    type: "text",
    placeholder: "Enter your subject...",
    errorMessage: "The subject should be at least 3 characters",
    label: "Subject",
    pattern: ".{3,50}",
    required: true,
  },
  {
    id: "4",
    name: "message",
    type: "text",
    placeholder: "Enter your subject...",
    errorMessage: "The message should be at least 5 characters",
    label: "Message",
    pattern: ".{5,250}",
    required: true,
    isLast: true,
    isTextArea: true,
  },
];
